### ISSUE TITLE
感謝樓主提供這好介面 但是我的系統是windwos 出現系統找不到指定的路徑。 請按任意鍵繼續 . . .

### ISSUE THREAD

**Issue by huddlesklar** [Hellohistory/EbookDatabase#5]
感謝樓主提供這好介面 但是我的系統是windwos 出現系統找不到指定的路徑。 請按任意鍵繼續 . . .
或是您能幫我查一下 這本書的喵傳連接 感謝 
SSID：13566792

DXID：000030020116

**Comment by Hellohistory** [comment]
软件出现些许bug请等待下一个版本的更新，这本书的话数据库好像没找到，能提供一下ISBN或者书名的话我可以再试试

**Comment by Hellohistory** [comment]
请下载最新版本
