### ISSUE TITLE
建议，谈不上issue

### ISSUE THREAD

**Issue by zazhi4** [Hellohistory/EbookDatabase#7]
读秀，本来就流传了一个所谓512W的数据，该数据含有书名，出版社，年份，SS号，读秀号，作者等信息（记不清了，可能更多）。该数据可以用来检索。另外，秒传码现在外面也流传了2.0-5.0的长码，短码。再有就是6.0也有流出。
能否整合一下所有信息，能够：1，能检索各种信息；2，如果有秒传码，则提供。不要因为没有秒传码，就不让检索到文件信息。
最后，也可以在readme告知大家，整合过程，比如，经过去重，一共有书X册，有秒传码Y条，对应书Z册。（有的书对应几条秒传码）

**Comment by Hellohistory** [comment]
实在很抱歉，有一些原因，没办法这么直接去提供相关信息，大家能明白这个是干嘛的就行了，广而告之的话会有一些不必要的事情，我本人还是希望这个项目能存活更久一些
