### ISSUE TITLE
不能访问127.0.0.1

### ISSUE THREAD

**Issue by zazhi4** [Hellohistory/EbookDatabase#8]
Win11
将软件包解压，将.db文件放到指定的文件夹。执行启动.bat。
执行后显示cmd窗口，按任意键继续，保留cmd窗口。这时Edge访问127.0.0.1：端口号，无法连接。
到cmd窗口，按了任意见，cmd窗口自动关闭。在Egde访问127.0.0.1：端口号，无法连接。

**Comment by Hellohistory** [comment]
请根据readme的bug反馈来提供您的相关错误信息，以便于复现错误找到问题帮助您

**Comment by zazhi4** [comment]
我是Win11系统
本机没有python.
已经将数据库放到了指定文件夹。
执行启动.bat后，我看哔哩哔哩视频，在cmd窗口该有多行文字，最下一行显示了127.0.0.1链接带端口。
但是我cmd窗口，只有一行文字，按任意键继续。
按了任意键后，窗口消失了。
具体见附件。




dong
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hellohistory/EbookDatabase"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月26日(星期四) 上午10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hellohistory/EbookDatabase] 不能访问127.0.0.1 (Issue #8)





 
请根据readme的bug反馈来提供您的相关错误信息，以便于复现错误找到问题帮助您

**Comment by zazhi4** [comment]
刚才邮件带的附件，不符合要求，重新贴图片。
图片1，2，执行启动.bat后，窗口显示：按任意键继续。与教程不一致。
图片3，文件夹下已经放了数据库
图片4，红框两个文件，activate.bat，python.exe，双击后都是闪退。


dong
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hellohistory/EbookDatabase"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月26日(星期四) 上午10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hellohistory/EbookDatabase] 不能访问127.0.0.1 (Issue #8)





 
请根据readme的bug反馈来提供您的相关错误信息，以便于复现错误找到问题帮助您

**Comment by zazhi4** [comment]
![2023-10-26_114311](https://github.com/Hellohistory/EbookDatabase/assets/139413038/ed6520c2-5064-4897-81b9-1e84c3de821e)
![2023-10-26_114345
![2023-10-26_114441](https://github.com/Hellohistory/EbookDatabase/assets/139413038/cb0d68c8-e7b2-4265-87b3-c116471396dc)

![2023-10-26_114400](https://github.com/Hellohistory/EbookDatabase/assets/139413038/cc85a59e-e118-49c0-b8db-2c9347ed93f9)
](https://github.com/Hellohistory/EbookDatabase/assets/139413038/5b9c8b78-0ad9-4f2c-8f74-144c4a3ae05e)

**Comment by zazhi4** [comment]
![2023-10-26_114345](https://github.com/Hellohistory/EbookDatabase/assets/139413038/f14a3241-8f83-4513-87e7-742df27dd371)

**Comment by zazhi4** [comment]
问题未解决

**Comment by Hellohistory** [comment]
日志文件打开看一下有没有内容

**Comment by MengHaiwangyang** [comment]
我的问题跟楼主描述的一样。

**Comment by Hellohistory** [comment]
请各位下载最新版本
