### ISSUE TITLE
发行版本很好，能够增加两个词或多个词的检索；还有按照时间倒叙排列

### ISSUE THREAD

**Issue by sci268** [Hellohistory/EbookDatabase#9]
发行版本很好，能够增加两个词或多个词的检索；还有按照时间倒叙排列。
感谢您的好软件，好人一个！祝福一切顺利！

**Comment by Hellohistory** [comment]
多个词检索可以增加，时间排序的话数据库资料不全，可能会出现问题，这个需要后面研究如何升级
